services:
  - type: web
    name: valtrix-clientes
    env: python
    plan: free
    buildCommand: "npm install && npm run build && pip install -r requirements.txt"
    startCommand: "gunicorn src.app:app"
    envVars:
      - key: PORT
        value: 10000
      - key: API_SECRET
        sync: false
