"""Refactored Sale ID

Revision ID: 13a990fa0709
Revises: 6f69379130cb
Create Date: 2026-05-09 21:25:27.410432

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '13a990fa0709'
down_revision = '6f69379130cb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('preference_id', sa.String(length=100), nullable=True))
        batch_op.alter_column('id',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.create_unique_constraint(None, ['preference_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False,
               autoincrement=True)
        batch_op.drop_column('preference_id')

    # ### end Alembic commands ###
